
POSTGRES_SQL_USERNAME: postgres
POSTGRES_SQL_PASSWORD: 12345
POSTGRES_SQL_HOST: 192.168.1.216
POSTGRES_SQL_PORT: 5432
POSTGRES_SQL_DB: spcloud

#Server
SERVER_PORT: 9000
ACTIVE_PROFILE: dev

#Email Config
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: raminqehramanzade146@gmail.com
EMAIL_PASSWORD: almvfwsjwlgtzdea
VERIFY_EMAIL_HOST: http://localhost:${SERVER_PORT}